name: Reactアプリのビルド確認

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリ取得
        uses: actions/checkout@v4
      - name: Node.js設定
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: 依存関係をインストール
        run: npm install
      - name: Reactアプリをビルド
        run: npm run build
